#nome dell'eseguibile da generare
PROG = hello-world

# lista dei sorgenti separati da spazi
SOURCES = hello-world.cpp

# flags del compilatore (ad es. -g per il debug)
CFLAGS = -g 

# nome del compilatore (gcc, g++, ecc)
CC = g++

# regola per la compilazione dell'eseguibile
hello-world: hello-world.cpp
	$(CC) $(CFLAGS) -o $(PROG) $(SOURCES)
